### ISSUE TITLE
Add basic administrative functionality

### ISSUE THREAD

**Issue by rbreslow** [rbreslow/zs#11]
Commands:

- [ ] Ban
- [ ] Ban IP
- [ ] Kick
- [ ] Unban
- [ ] Map
- [ ] Mute (Prevent text/voice chat)
- [ ] Unmute
- [ ] Modify Rank

Functionality:

- Show how many admins are online.
- Have a way of DMing an admin.
- Wish List: VGUI for executing these commands, listing bans.

**Comment by johnnymoe** [comment]
Administrators should have full privileges. Let's delegate the following to moderators:

1. Ban
2. Ban IP
3. Kick
4. Unban
5. Mute
6. Unmute
