### ISSUE TITLE
Set `Enable Movement Roll` from Options Menu to disabled by default

### ISSUE THREAD

**Issue by johnnymoe** [rbreslow/zs#22]

**Comment by Galaco** [comment]
As best as I can see, it already is disabled by default:
https://github.com/rbreslow/zs/blob/ff19e20c0089477edd5a275ae8267e2bb89bbd79/src/garrysmod/gamemodes/zombiesurvival/gamemode/cl_options.lua#L232

Could i get confirmation that this isn't the current behaviour?

**Comment by johnnymoe** [comment]
It may have just been my end. If so— this issue can be closed.

**Comment by Galaco** [comment]
It was disabled for me, and I don't believe I've ever touched that setting (didn't know it existed tbh). The Cvar is marked as disabled by default, so I'll be closing this. If it does come up again for whatever reason we can revisit it.
